# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2643433acc9204bc67abf4fb29175a8faa4e2d757c3dda1582c70217d754d93a4b1f244b2d9c8ecf046c78901999acbebf75a8dc0eaaab4b5ba1d5df21aad4a1

test:
  secret_key_base: 362366adf2f3345e7ebe6faa4c3a09da09ce4a6d8d1c941eb1d8931e6eb3ed735a8ea091afef4947cb3a3db6b4241301e511b0db55a2cd0a4e3cd587e1e181bb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
